// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/api/joke.ts";
import * as $2 from "./routes/demo/index.tsx";
import * as $3 from "./routes/index.tsx";
import * as $4 from "./routes/mission/index.tsx";
import * as $5 from "./routes/team/index.tsx";
import * as $6 from "./routes/waitlist/index.tsx";
import * as $$0 from "./islands/Footer.tsx";
import * as $$1 from "./islands/Navbar.tsx";
import * as $$2 from "./islands/Video.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/api/joke.ts": $1,
    "./routes/demo/index.tsx": $2,
    "./routes/index.tsx": $3,
    "./routes/mission/index.tsx": $4,
    "./routes/team/index.tsx": $5,
    "./routes/waitlist/index.tsx": $6,
  },
  islands: {
    "./islands/Footer.tsx": $$0,
    "./islands/Navbar.tsx": $$1,
    "./islands/Video.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
